name: "Deploy Release"
on:
  push:
    branches:
      - main
    paths:
      - "addons/**"
      - '.github/workflows/deploy-release.yml'
  workflow_dispatch:

env:
  PLUGIN_NAME: animated_panel_container_gd

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
        
      - name: Get Version
        run: |
          echo "PLUGIN_VERSION=$(grep 'version=' addons/${{env.PLUGIN_NAME}}/plugin.cfg | sed -e 's/version=//' -e 's/\"//g')" >> $GITHUB_ENV

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./addons/${{env.PLUGIN_NAME}}
          publish_branch: release
          enable_jekyll: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "deploy: Updated to ${{env.PLUGIN_VERSION}}"
